DROP TABLE IF EXISTS playlists CASCADE;

CREATE TABLE playlists (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) REFERENCES users(id) ON DELETE CASCADE
);